
package webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-16T11:32:49.559+02:00
 * Generated source version: 3.0.1
 * 
 */
public final class IPersonaSoap_PersonaSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice/", "PersonaSoapService");

    private IPersonaSoap_PersonaSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PersonaSoapService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PersonaSoapService ss = new PersonaSoapService(wsdlURL, SERVICE_NAME);
        IPersonaSoap port = ss.getPersonaSoapPort();  
        
        {
        System.out.println("Invoking eliminarPersona...");
        java.lang.Integer _eliminarPersona_arg0 = null;
        port.eliminarPersona(_eliminarPersona_arg0);


        }
        {
        System.out.println("Invoking obtenerPersona...");
        java.lang.Integer _obtenerPersona_arg0 = null;
        webservice.PersonaTo _obtenerPersona__return = port.obtenerPersona(_obtenerPersona_arg0);
        System.out.println("obtenerPersona.result=" + _obtenerPersona__return);


        }
        {
        System.out.println("Invoking agregarPersona...");
        webservice.PersonaTo _agregarPersona_arg0 = null;
        port.agregarPersona(_agregarPersona_arg0);


        }
        {
        System.out.println("Invoking modificarPersona...");
        webservice.PersonaTo _modificarPersona_arg0 = null;
        port.modificarPersona(_modificarPersona_arg0);


        }
        {
        System.out.println("Invoking obtenerPersonas...");
        java.util.List<webservice.PersonaTo> _obtenerPersonas__return = port.obtenerPersonas();
        System.out.println("obtenerPersonas.result=" + _obtenerPersonas__return);


        }

        System.exit(0);
    }

}
