package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-16T11:32:49.641+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "PersonaSoapService", 
                  wsdlLocation = "http://localhost:8080/Ejercicio2Servidor/ws/PersonaSoap?wsdl",
                  targetNamespace = "http://webservice/") 
public class PersonaSoapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "PersonaSoapService");
    public final static QName PersonaSoapPort = new QName("http://webservice/", "PersonaSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Ejercicio2Servidor/ws/PersonaSoap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonaSoapService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Ejercicio2Servidor/ws/PersonaSoap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonaSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonaSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonaSoapService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonaSoapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonaSoapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonaSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IPersonaSoap
     */
    @WebEndpoint(name = "PersonaSoapPort")
    public IPersonaSoap getPersonaSoapPort() {
        return super.getPort(PersonaSoapPort, IPersonaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPersonaSoap
     */
    @WebEndpoint(name = "PersonaSoapPort")
    public IPersonaSoap getPersonaSoapPort(WebServiceFeature... features) {
        return super.getPort(PersonaSoapPort, IPersonaSoap.class, features);
    }

}
