package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-15T10:41:57.445+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "CalculadoraSoapService", 
                  wsdlLocation = "http://localhost:8080/Ejercicio1Servidor/ws/CalculadoraSoap?wsdl",
                  targetNamespace = "http://webservice/") 
public class CalculadoraSoapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "CalculadoraSoapService");
    public final static QName CalculadoraSoapPort = new QName("http://webservice/", "CalculadoraSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Ejercicio1Servidor/ws/CalculadoraSoap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculadoraSoapService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Ejercicio1Servidor/ws/CalculadoraSoap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculadoraSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculadoraSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraSoapService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalculadoraSoapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalculadoraSoapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalculadoraSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ICalculadoraSoap
     */
    @WebEndpoint(name = "CalculadoraSoapPort")
    public ICalculadoraSoap getCalculadoraSoapPort() {
        return super.getPort(CalculadoraSoapPort, ICalculadoraSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICalculadoraSoap
     */
    @WebEndpoint(name = "CalculadoraSoapPort")
    public ICalculadoraSoap getCalculadoraSoapPort(WebServiceFeature... features) {
        return super.getPort(CalculadoraSoapPort, ICalculadoraSoap.class, features);
    }

}
